FROM tutum/lamp:latest
# RUN rm -fr /app && git clone https://github.com/stvvt/bgerp.git /app

RUN apt-get update && apt-get install -y software-properties-common php5-imap php5-gd php5-curl wget wkhtmltopdf xvfb ghostscript imagemagick \
    zbar-tools swftools xpdf-utils p7zip-full default-jre unoconv
    
RUN apt-add-repository ppa:inkscape.dev/stable
RUN apt-get update && apt-get install -y inkscape tnef
    
RUN a2enmod headers rewrite
RUN php5enmod imap gd curl

COPY ./_docs/docker/mysql-setup.sh /mysql-setup.sh

COPY . /app/bgerp

RUN mkdir /app/conf

RUN cp -a /app/bgerp/_docs/docker/conf/docker.cfg.php /app/conf/bgerp.cfg.php
RUN cp -a /app/bgerp/_docs/webroot /app/

RUN echo  >> /app/webroot/index.cfg.php
RUN echo "// Autogenerated" >> /app/webroot/index.cfg.php
RUN echo "DEFINE('EF_ROOT_PATH', '/app');" >> /app/webroot/index.cfg.php
RUN echo "DEFINE('EF_APP_NAME', 'bgerp');" >> /app/webroot/index.cfg.php
RUN echo "DEFINE('CORE_OVERWRITE_HTAACCESS', false);" >> /app/webroot/index.cfg.php

COPY ./_docs/docker/apache-default /etc/apache2/sites-available/000-default.conf

VOLUME ["/app/uploads"]

RUN chmod 777 /app/webroot

EXPOSE 80 3306
CMD ["/run.sh"]